name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose another OS like macOS or Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Use Node.js 22.x to match your local version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
